un makefile est un fichier qui permet de lire des regles qui vont generer 
des programmes en compilant seulement les parties modifiées.


    [syntaxe :]

<target> : <pre-requisites>
	<recipe>

    [ex:]

hello: hello.c hellofun.c
    gcc -o hello hello.c hellofun.c -i

(compile hello.c && hellofun.c en hello)


----------------------------------------

all: file1   
    cat file1 > file2

file1:
    echo "hello" > file1

$(Var_name) call a variable


-----------------------------------------

clean:
    rm file1 file2 

spécial var :
 $@ -> current target
 $< -> first dependencies
 $^ -> dependencies list
 $? -> dependencies list recently updates
 $* -> file name without his extension


-----------------------------------------

    [conditions :]

ifndef

ifeq ($(var_name), <value>)
	<command>

else
	<command>

-----------------------------------------

[spécial]

.DEFAULT_GOAL = help -> permet l'execution d'une cible simplement avec un make

## for comments 